### ISSUE TITLE
Meet the errors when run osc_cli command

### ISSUE THREAD

**Issue by lynch0227** [facebookincubator/OnlineSchemaChange#10]
Hi Guys,
  When I run the osc command, I got the below errors:
ERROR     2017-05-25 09:55:57.633 NOT_RBR_SAFE: Running OSC with RBR is not safe for a non-FB MySQL version. You will need to either have "sql_log_bin_triggers" supported and enabled, or disable RBR before running OSC
  I find that because I use the mysql community version, not the facebook, so does't have sql_log_bin_triggers parameter.
  Can you modify the is_trigger_rbr_safe function in core/lib/payload/copy.py to avoid this issue?

Thank you.

**Comment by cenalulu** [comment]
Hi @lynch0227,

Thanks for the report. Currently OSC doesn't support running on community version when RBR is enabled. The detailed reason behind it can be find  in [this wiki Q&A session](https://github.com/facebookincubator/OnlineSchemaChange/wiki/Q-%26-A#why-osc-doesnt-work-on-rbr)
Before we adding support for this combination, it's safer to avoid running in such environment.

**Comment by cenalulu** [comment]
Feature request created for this: https://github.com/facebookincubator/OnlineSchemaChange/issues/11
Closing this issue for now, since this is expected with current implementation and explained in the wiki.
